---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
      - id: check-json
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      # - id: pretty-format-json
      #  args: ['--no-sort-keys']
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: [--branch, release]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
  # - repo: "https://github.com/gruntwork-io/pre-commit"
  #   rev: "v0.1.22" # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  #   hooks:
  #     - id: "helmlint"
  # - repo: https://github.com/bridgecrewio/checkov.git
  #   rev: 2.3.309
  #   hooks:
  #     - id: checkov
  #       args: [-d .]
  # - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
  #   rev: v0.1.0
  #   hooks:
  #     - id: k8svalidate
  #       files: .yaml$
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #     - id: detect-secrets
  - repo: "https://github.com/norwoodj/helm-docs"
    rev: "v1.11.0"
    hooks:
      - id: "helm-docs"
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - "--chart-search-root=charts"

          # The `./` makes it relative to the chart-search-root set above
          - "--template-files=README.md.gotmpl"

  - repo: "https://github.com/norwoodj/helm-docs"
    rev: "v1.11.0"
    hooks:
      - id: "helm-docs"
        args:
          - "--chart-to-generate=charts/nautobot"
          - "--template-files=./docs/configuration/reference.md.gotmpl"
          - "--output-file=../../docs/configuration/reference.md"
