namespaces:
  - name: parent
    is_sub_namespace: false
    annotations:
      prometheus.io/port: 8080
      prometheus.io/scrape: true
    labels:
      kustomize.toolkit.fluxcd.io/name: namespaces
      kustomize.toolkit.fluxcd.io/namespace: parent
  - name: parent-2
    is_sub_namespace: false
    annotations:
      prometheus.io/port: 8080
      prometheus.io/scrape: true
    labels:
      kustomize.toolkit.fluxcd.io/name: namespaces
      kustomize.toolkit.fluxcd.io/namespace: parent
  - name: child1
    is_sub_namespace: true
    parent: parent
    annotations:
      prometheus.io/port: 8080
      prometheus.io/scrape: true
    labels:
      kustomize.toolkit.fluxcd.io/name: namespaces
      kustomize.toolkit.fluxcd.io/namespace: parent
  - name: child2
    is_sub_namespace: true
    parent: parent
    annotations:
      prometheus.io/port: 8080
      prometheus.io/scrape: true
    labels:
      kustomize.toolkit.fluxcd.io/name: namespaces
      kustomize.toolkit.fluxcd.io/namespace: parent
  - name: tenant1
    is_sub_namespace: true
    parent: parent-2
    annotations:
      prometheus.io/port: 8080
      prometheus.io/scrape: true
    labels:
      kustomize.toolkit.fluxcd.io/name: namespaces
      kustomize.toolkit.fluxcd.io/namespace: parent
  - name: tenant2
    is_sub_namespace: true
    parent: parent-2
    annotations:
      prometheus.io/port: 8080
      prometheus.io/scrape: true
    labels:
      kustomize.toolkit.fluxcd.io/name: namespaces
      kustomize.toolkit.fluxcd.io/namespace: parent
