name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: [self-hosted, linux, ARM64, default]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "arm64"
      - uses: pre-commit/action@v3.0.0
