name: pre-commit

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - release
jobs:
  pre-commit:
    runs-on: [self-hosted, linux, X64, default]
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
