name: pre-commit

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ["self-hosted", "macOS", "ARM64"]
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
