---
name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  release:
    permissions:
      contents: write
    runs-on: [self-hosted, linux, X64, default]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      - name: Add dependency chart repos
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm repo add minio https://helm.min.io

      - name: Publish Helm Charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_url: https://svil-helm-charts.srivittal.com/
          token: "${{ secrets.GITHUB_TOKEN }}"

      # - name: Push helm charts
      #   # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.5.0
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     CR_SKIP_EXISTING: false
